In [1]:
import pandas as pd
import plotly.express as px
import sqlite3
import numpy as np

In [2]:
conn = sqlite3.connect('data.db')

In [3]:
maven_dict = pd.read_csv('Raw_Data/maven_fuzzy_factory_data_dictionary.csv')
refunds = pd.read_csv('Raw_Data/order_item_refunds.csv')
order_items = pd.read_csv('Raw_Data/order_items.csv')
orders = pd.read_csv('Raw_Data/orders.csv')
products = pd.read_csv('Raw_Data/products.csv')
website_views = pd.read_csv('Raw_Data/website_pageviews.csv')
website_session = pd.read_csv('Raw_Data/website_sessions.csv')

In [4]:
order_items.head()

,order_item_id,created_at,order_id,product_id,is_primary_item,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,1,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,2,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,3,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,4,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,5,1,1,49.99,19.49

In [5]:
'''
Table: 
order_items

Purpose: 
Shows products purchased

Granularity:
1 row = 1 purchased product

Primary key: 
order_item_id

Connects to: 
- orders table by column name 'order_id'

Important columns: 
- order_item_id
- created_at
- product_id
- order_id
- price_usd
- cogs_usd
- is_primary_item

Possible analysis:
- total revenue/ profits
- profit margins
- best selling products
- product performance

'''

"\nTable: \norder_items\n\nPurpose: \nShows products purchased\n\nGranularity:\n1 row = 1 purchased product\n\nPrimary key: \norder_item_id\n\nConnects to: \n- orders table by column name 'order_id'\n\nImportant columns: \n- order_item_id\n- created_at\n- product_id\n- order_id\n- price_usd\n- cogs_usd\n- is_primary_item\n\nPossible analysis:\n- total revenue/ profits\n- profit margins\n- best selling products\n- product performance\n\n"

In [6]:
orders.head()

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,20,20,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,104,104,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,147,147,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,160,160,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,177,177,1,1,49.99,19.49

In [7]:
'''
Table:
Orders

Stores:
customer purchase information along with website session.

Granularity:
1 row = 1 customer order

Primary key:
order_id

Connects to:
- Website_sessions by column 'website_session_id'
- order_items by column 'order_id'

Important columns:
- order_id
- website_session_id
- user_id
- primary_product_id
- items_purchased
- price_usd
- cogs_usd
- created_at

Possible analysis:
- Total revenue and profit
- profit margins
- Orders per customer
- sales trend
- time insights
'''

"\nTable:\nOrders\n\nStores:\ncustomer purchase information along with website session.\n\nGranularity:\n1 row = 1 customer order\n\nPrimary key:\norder_id\n\nConnects to:\n- Website_sessions by column 'website_session_id'\n- order_items by column 'order_id'\n\nImportant columns:\n- order_id\n- website_session_id\n- user_id\n- primary_product_id\n- items_purchased\n- price_usd\n- cogs_usd\n- created_at\n\nPossible analysis:\n- Total revenue and profit\n- profit margins\n- Orders per customer\n- sales trend\n- time insights\n"

In [8]:
website_session

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 08:37:33,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,2012-03-19 09:00:55,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
...,...,...,...,...,...,...,...,...,...
472866,472867,2015-03-19 07:49:25,394314,0,gsearch,brand,g_ad_2,desktop,https://www.gsearch.com
472867,472868,2015-03-19 07:54:36,394315,0,bsearch,nonbrand,b_ad_1,mobile,https://www.bsearch.com
472868,472869,2015-03-19 07:55:40,394316,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
472869,472870,2015-03-19 07:56:29,394317,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
472870,472871,2015-03-19 07:59:08,394318,0,NaN,NaN,NaN,mobile,NaN

In [9]:
'''

Table:
website_sessions

Stores:
instances where website was visited by users and marketing information

Granularity:
1 row = 1 website visit

Primary key:
website_session_id

Connects to:
- orders by 'website_session_id' 
- website_pageviews by 'website_session_id'

Important columns:
- website_session_id
- created_at
- user_id
- utm_source
- utm_campaign
- utm_content
- device_type

Possible analysis:
- most effective campaign
- device type insights
- website visit trends
- conversion rates
- customer acquisition channels
'''

"\n\nTable:\nwebsite_sessions\n\nStores:\ninstances where website was visited by users and marketing information\n\nGranularity:\n1 row = 1 website visit\n\nPrimary key:\nwebsite_session_id\n\nConnects to:\n- orders by 'website_session_id' \n- website_pageviews by 'website_session_id'\n\nImportant columns:\n- website_session_id\n- created_at\n- user_id\n- utm_source\n- utm_campaign\n- utm_content\n- device_type\n\nPossible analysis:\n- most effective campaign\n- device type insights\n- website visit trends\n- conversion rates\n- customer acquisition channels\n"

In [10]:
website_views

,website_pageview_id,created_at,website_session_id,pageview_url
0,1,2012-03-19 08:04:16,1,/home
1,2,2012-03-19 08:16:49,2,/home
2,3,2012-03-19 08:26:55,3,/home
3,4,2012-03-19 08:37:33,4,/home
4,5,2012-03-19 09:00:55,5,/home
...,...,...,...,...
1188119,1188120,2015-03-19 07:57:32,472866,/shipping
1188120,1188121,2015-03-19 07:58:13,472870,/the-original-mr-fuzzy
1188121,1188122,2015-03-19 07:59:07,472866,/billing-2
1188122,1188123,2015-03-19 07:59:08,472871,/home
1188123,1188124,2015-03-19 07:59:32,472868,/the-original-mr-fuzzy

In [11]:
'''
Table:
website_pageviews

Stores:
A customers journey through the website

Granularity:
1 row = 1 page viewed during a website session

Primary key:
website_pageview_id

Connects to:
website_sessions by 'website_session_id'

Important columns:
- created_at
- website_session_id
- pageview_url

Possible analysis
- most pages visited
- Customer journey
- checkout behaviour

'''

"\nTable:\nwebsite_pageviews\n\nStores:\nA customers journey through the website\n\nGranularity:\n1 row = 1 page viewed during a website session\n\nPrimary key:\nwebsite_pageview_id\n\nConnects to:\nwebsite_sessions by 'website_session_id'\n\nImportant columns:\n- created_at\n- website_session_id\n- pageview_url\n\nPossible analysis\n- most pages visited\n- Customer journey\n- checkout behaviour\n\n"

In [12]:
refunds

,order_item_refund_id,created_at,order_item_id,order_id,refund_amount_usd
0,1,2012-04-06 11:32:43,57,57,49.99
1,2,2012-04-13 01:09:43,74,74,49.99
2,3,2012-04-15 07:03:48,71,71,49.99
3,4,2012-04-17 20:00:37,118,118,49.99
4,5,2012-04-22 20:53:49,116,116,49.99
...,...,...,...,...,...
1726,1727,2015-03-30 09:37:23,39950,32255,59.99
1727,1728,2015-03-30 21:33:51,39671,32049,49.99
1728,1729,2015-03-31 19:59:48,39729,32090,49.99
1729,1730,2015-04-01 03:54:48,39717,32079,59.99
1730,1731,2015-04-01 18:11:08,39947,32252,45.99

In [13]:
'''
Table:
order_items_refunds

Stores:
orders that got refunded

Granularity:
1 row = 1 refunded order item

Primary key:
order_item_refund_id

connects to:
- order_items by 'order_item_id'

Important columns:
- created_at
- refund_amount_usd
- order_id
- order_item_id

Possible analysis:
- refund trends
- refund rate by product
- total refunds per product
- profit loss due to refund
- refund impact on margins

'''

"\nTable:\norder_items_refunds\n\nStores:\norders that got refunded\n\nGranularity:\n1 row = 1 refunded order item\n\nPrimary key:\norder_item_refund_id\n\nconnects to:\n- order_items by 'order_item_id'\n\nImportant columns:\n- created_at\n- refund_amount_usd\n- order_id\n- order_item_id\n\nPossible analysis:\n- refund trends\n- refund rate by product\n- total refunds per product\n- profit loss due to refund\n- refund impact on margins\n\n"

In [14]:
products

   product_id           created_at                product_name
0           1  2012-03-19 08:00:00      The Original Mr. Fuzzy
1           2  2013-01-06 13:00:00       The Forever Love Bear
2           3  2013-12-12 09:00:00    The Birthday Sugar Panda
3           4  2014-02-05 10:00:00  The Hudson River Mini bear

In [15]:
'''
Table:
products

Stores:
Product information 

Granularity:
1 row = 1 product information

Primary key:
product_id

Connects to:
order_items by 'product_id'

Important columns:
- product_id
- product_name

Possible analysis:
- product categorisation
- product sales performance
- product profitability
- product popularity
- product refund rates

'''

"\nTable:\nproducts\n\nStores:\nProduct information \n\nGranularity:\n1 row = 1 product information\n\nPrimary key:\nproduct_id\n\nConnects to:\norder_items by 'product_id'\n\nImportant columns:\n- product_id\n- product_name\n\nPossible analysis:\n- product categorisation\n- product sales performance\n- product profitability\n- product popularity\n- product refund rates\n\n"

In [16]:
maven_dict[maven_dict['Table'] == 'order_items']

,Table,Field,Description
8,order_items,order_item_id,Unique identifier for each order item (PK)
9,order_items,created_at,Timestamp when the order was placed
10,order_items,order_id,Unique identifier for the order the item belon...
11,order_items,product_id,Unique identifier for the product (FK)
12,order_items,is_primary_item,Binary flag with a value of 1 if it's the prim...
13,order_items,price_usd,Price of the product
14,order_items,cogs_usd,Cost of goods sold of the product

In [17]:
maven_dict['Table'].value_counts()

Table
website_sessions      9
orders                8
order_items           7
order_item_refunds    5
website_pageviews     4
products              3
Name: count, dtype: int64

In [18]:
refunds

,order_item_refund_id,created_at,order_item_id,order_id,refund_amount_usd
0,1,2012-04-06 11:32:43,57,57,49.99
1,2,2012-04-13 01:09:43,74,74,49.99
2,3,2012-04-15 07:03:48,71,71,49.99
3,4,2012-04-17 20:00:37,118,118,49.99
4,5,2012-04-22 20:53:49,116,116,49.99
...,...,...,...,...,...
1726,1727,2015-03-30 09:37:23,39950,32255,59.99
1727,1728,2015-03-30 21:33:51,39671,32049,49.99
1728,1729,2015-03-31 19:59:48,39729,32090,49.99
1729,1730,2015-04-01 03:54:48,39717,32079,59.99
1730,1731,2015-04-01 18:11:08,39947,32252,45.99

In [19]:
tables = {
    'orders' : orders,
    'order_items' : order_items,
    'order_item_refund' : refunds,
    'website_sessions' : website_session,
    'website_pageviews' : website_views
}

In [20]:
primary_keys = {
    'orders' : 'order_id',
    'order_items' : 'order_item_id',
    'order_item_refund' : 'order_item_refund_id',
    'website_sessions' : 'website_session_id',
    'website_pageviews' : 'website_pageview_id'
}

In [21]:
for name, table in tables.items():
    print('----------------------------------------')
    print(f'Table name : {name}')
    print(f'shape = {table.shape}')

    pk = primary_keys[name] 

    print(f'duplicated values = {table.duplicated().sum()}')
    print(f'Primary key duplicates : {table[pk].duplicated().sum()}')

    print('--------------------')
    print('NAN CHECK:')
    print(table.isna().sum())
    print('--------------------')
    print('DATA TYPE CHECK:')
    print(table.dtypes)

----------------------------------------
Table name : orders
shape = (32313, 8)
duplicated values = 0
Primary key duplicates : 0
--------------------
NAN CHECK:
order_id              0
created_at            0
website_session_id    0
user_id               0
primary_product_id    0
items_purchased       0
price_usd             0
cogs_usd              0
dtype: int64
--------------------
DATA TYPE CHECK:
order_id                int64
created_at                str
website_session_id      int64
user_id                 int64
primary_product_id      int64
items_purchased         int64
price_usd             float64
cogs_usd              float64
dtype: object
----------------------------------------
Table name : order_items
shape = (40025, 7)
duplicated values = 0
Primary key duplicates : 0
--------------------
NAN CHECK:
order_item_id      0
created_at         0
order_id           0
product_id         0
is_primary_item    0
price_usd          0
cogs_usd           0
dtype: int64
--------------------
DATA TYPE CHECK:
order_item_id        int64
created_at             str
order_id             int64
product_id           int64
is_primary_item      int64
price_usd          float64
cogs_usd           float64
dtype: object
----------------------------------------
Table name : order_item_refund
shape = (1731, 5)
duplicated values = 0
Primary key duplicates : 0
--------------------
NAN CHECK:
order_item_refund_id    0
created_at              0
order_item_id           0
order_id                0
refund_amount_usd       0
dtype: int64
--------------------
DATA TYPE CHECK:
order_item_refund_id      int64
created_at                  str
order_item_id             int64
order_id                  int64
refund_amount_usd       float64
dtype: object
----------------------------------------
Table name : website_sessions
shape = (472871, 9)
duplicated values = 0
Primary key duplicates : 0
--------------------
NAN CHECK:
website_session_id        0
created_at                0
user_id                   0
is_repeat_session         0
utm_source            83328
utm_campaign          83328
utm_content           83328
device_type               0
http_referer          39917
dtype: int64
--------------------
DATA TYPE CHECK:
website_session_id    int64
created_at              str
user_id               int64
is_repeat_session     int64
utm_source              str
utm_campaign            str
utm_content             str
device_type             str
http_referer            str
dtype: object
----------------------------------------
Table name : website_pageviews
shape = (1188124, 4)
duplicated values = 0
Primary key duplicates : 0
--------------------
NAN CHECK:
website_pageview_id    0
created_at             0
website_session_id     0
pageview_url           0
dtype: int64
--------------------
DATA TYPE CHECK:
website_pageview_id    int64
created_at               str
website_session_id     int64
pageview_url             str
dtype: object

In [22]:
for name, df in tables.items():

    df['created_at'] = pd.to_datetime(df['created_at'])

In [23]:
def traffic_source(row):

    if pd.notna(row['utm_source']):
        return row['utm_source']
    
    elif pd.notna(row['http_referer']):
        return 'organic'
    
    else:
        return 'direct'
    
website_session['traffic_source'] = website_session.apply(traffic_source, axis=1)

In [24]:
website_session.to_sql('website_session', conn, if_exists='replace', index=False)
website_views.to_sql('website_pageviews', conn, if_exists='replace', index=False)
order_items.to_sql('order_items', conn, if_exists='replace', index=False)
orders.to_sql('orders', conn, if_exists='replace', index=False)
refunds.to_sql('order_item_refunds', conn, if_exists='replace', index=False)
products.to_sql('products', conn, if_exists='replace', index=False)
maven_dict.to_sql('maven_dict', conn, if_exists='replace', index=False)

36

In [25]:
dfs = pd.read_sql('''
Select name
FROM sqlite_master
WHERE type = 'table'                  
                     ''', conn
)

In [26]:
dfs

                 name
0     website_session
1   website_pageviews
2         order_items
3              orders
4  order_item_refunds
5            products
6          maven_dict

In [27]:
orders_table = pd.read_sql('''
SELECT *
FROM orders                           
                           ''', conn, parse_dates=['created_at'])

In [28]:
orders_table['profit'] = orders_table['price_usd'] - orders_table['cogs_usd']
orders_table['month'] = orders_table['created_at'].dt.to_period('M')

In [29]:
total_revenue = orders_table['price_usd'].sum()
total_profit = orders_table['profit'].sum()
total_buying_customers = orders_table['user_id'].nunique()
total_items_sold = orders_table['items_purchased'].sum()
date_range = f'{orders_table['created_at'].min()} - {orders_table['created_at'].max()}'
profit_margin = (total_profit/total_revenue) * 100
average_order_value = total_revenue/len(orders_table)

In [30]:
orders_table_monthly = orders_table.groupby(['month'], as_index=False).agg(
    total_revenue = ('price_usd', 'sum'),
    total_profit = ('profit', 'sum'),
    total_orders = ('items_purchased', 'sum')
)
orders_table_monthly['month'] = orders_table_monthly['month'].astype(str)

In [31]:
fig = px.line(orders_table_monthly, x='month', y='total_revenue', title='revenue_by_month')
fig.show()

In [32]:
'''
General business insights

- Total revenue = $1,938,509
- Total profits = $1,216,139
- Total orders = 31,696
- Date range = 19/03/2012 - 19/03/2015
- Profit margin = 62%
- Average order value = $59.99

Initial revenue analysis shows consitent growth from 2012 to 2015 the business has been steadily increasing revenue driven by the increase in orders. It also shows
that at 2012 the business was at its early growth phase.

Revenue by time chart also shows some seasonality with spikes around the christmas period.
'''

'\nGeneral business insights\n\n- Total revenue = $1,938,509\n- Total profits = $1,216,139\n- Total orders = 31,696\n- Date range = 19/03/2012 - 19/03/2015\n- Profit margin = 62%\n- Average order value = $59.99\n\nInitial revenue analysis shows consitent growth from 2012 to 2015 the business has been steadily increasing revenue driven by the increase in orders. It also shows\nthat at 2012 the business was at its early growth phase.\n\nRevenue by time chart also shows some seasonality with spikes around the christmas period.\n'

In [33]:
product_data_sum = pd.read_sql('''                           
SELECT 
    p.product_name, 
    COUNT(oi.order_item_id) as total_orders,
    SUM(oi.price_usd) as total_revenue,
    SUM(oi.price_usd - oi.cogs_usd) as total_profit,
    ROUND(SUM(oi.price_usd - oi.cogs_usd) * 100.0/ SUM(oi.price_usd), 2) as profit_margin
                                                       
FROM order_items oi
LEFT JOIN products p
ON oi.product_id = p.product_id       
GROUP BY p.product_name
ORDER BY total_profit DESC                
                           ''', conn)

In [34]:
product_performance = pd.read_sql('''
SELECT 
    p.product_name, 
    oi.created_at, 
    oi.price_usd,
    oi.cogs_usd,
    oi.product_id,
    oi.order_item_id                                 
FROM order_items oi
LEFT JOIN products p
ON oi.product_id = p.product_id                                  
                                  ''', conn, parse_dates=['created_at'])

In [35]:
product_performance['monthly'] = product_performance['created_at'].dt.to_period('M')
product_performance['profit'] = product_performance['price_usd'] - product_performance['cogs_usd']

In [36]:
product_performance_data = product_performance.groupby(['monthly', 'product_name'], as_index=False).agg(
    total_orders = ('order_item_id', 'count'),
    total_revenue = ('price_usd', 'sum'),    
).sort_values(by='monthly')
product_performance_data['monthly'] = product_performance_data['monthly'].astype(str)

In [37]:
fig = px.line(product_performance_data, x = 'monthly', y='total_revenue', color='product_name', markers=True, title='monthly_revenue_by_product')
fig.show()

In [38]:
fig = px.line(product_performance_data, x='monthly', y='total_orders', color='product_name', markers=True, title = 'monthly_orders_by_product')
fig.show()

In [39]:
'''
Product Insights

The Original Mr.Fuzzy had the highest orders and revenue, likely because it was available for the entirety of the dataset. The other 3 products were introduced later. 
With The Forever Love Bear being introduced in 2013 and The Birthday Sugar Panda and The Hudson River Mini Bear being introduced in 2014.

The Original Mr.Fuzzy, had a stable uptrend in revenue and orders between 2012 to 2015. With The Forever Love Bear having a stable uptrend from
2013 to 2015 but a decline in orders and revenue from Feb 2015 to Mar 2015. The Birthday Sugar Panda and The Hudson River Mini Bear showed a nice uptrend 
in revenue and orders since its release although near the end of 2014 it started declining. However it is a fairly new product and the sample size 
is limited.


'''

'\nProduct Insights\n\nThe Original Mr.Fuzzy had the highest orders and revenue, likely because it was available for the entirety of the dataset. The other 3 products were introduced later. \nWith The Forever Love Bear being introduced in 2013 and The Birthday Sugar Panda and The Hudson River Mini Bear being introduced in 2014.\n\nThe Original Mr.Fuzzy, had a stable uptrend in revenue and orders between 2012 to 2015. With The Forever Love Bear having a stable uptrend from\n2013 to 2015 but a decline in orders and revenue from Feb 2015 to Mar 2015. The Birthday Sugar Panda and The Hudson River Mini Bear showed a nice uptrend \nin revenue and orders since its release although near the end of 2014 it started declining. However it is a fairly new product and the sample size \nis limited.\n\n\n'

In [40]:
product_refunds = pd.read_sql('''
SELECT 
    p.product_name,
    SUM(oi.price_usd) as total_product_revenue,
    COALESCE(SUM(oir.refund_amount_usd), 0) as total_refund_amount,
    COUNT(oir.order_item_refund_id) as total_product_refunds,
    COUNT(oi.order_item_id) as total_product_sold
    
    
FROM order_items oi
LEFT JOIN order_item_refunds oir
ON oi.order_item_id = oir.order_item_id
INNER JOIN products p
ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_refund_amount DESC                                                             
                              ''', conn)

In [41]:
product_refunds['product_refund_rate'] = ((product_refunds['total_product_refunds']/product_refunds['total_product_sold']) * 100).round(2)
product_refunds.sort_values(by='product_refund_rate', ascending=False)

,product_name,total_product_revenue,total_refund_amount,total_product_refunds,total_product_sold,product_refund_rate
1,The Birthday Sugar Panda,229260.15,13842.99,301,4985,6.04
0,The Original Mr. Fuzzy,1211057.74,61837.63,1237,24226,5.11
2,The Forever Love Bear,347702.04,7738.71,129,5796,2.23
3,The Hudson River Mini bear,150489.82,1919.36,64,5018,1.28

In [42]:
'''
Product Refund Insights

The Birthday Sugar Panda had the highest refund rate out of all the products. In terms of the total refund amount, The Original Mr. Fuzzy is the 
highest likely due to it being on the market the longest and having the most units sold. Yet the refund rate is lower than The Birthday Sugar Panda, which
in terms of the how long it has been on the market and the number of products sold. which is similar to The Forever Love Bear and The Hudson River Mini Bear.
The Birthday Sugar Panda has a significantly higher refund rate.

'''

'\nProduct Refund Insights\n\nThe Birthday Sugar Panda had the highest refund rate out of all the products. In terms of the total refund amount, The Original Mr. Fuzzy is the \nhighest likely due to it being on the market the longest and having the most units sold. Yet the refund rate is lower than The Birthday Sugar Panda, which\nin terms of the how long it has been on the market and the number of products sold. which is similar to The Forever Love Bear and The Hudson River Mini Bear.\nThe Birthday Sugar Panda has a significantly higher refund rate.\n\n'

In [43]:
marketing_info = pd.read_sql('''
SELECT 
    ws.website_session_id,
    o.order_id,
    o.website_session_id,
    ws.device_type,
    ws.utm_source,
    ws.utm_campaign
FROM website_session ws
LEFT JOIN orders o
ON ws.website_session_id	= o.website_session_id                         
                             ''', conn)

In [44]:
marketing_info

,website_session_id,order_id,website_session_id,device_type,utm_source,utm_campaign
0,1,NaN,NaN,mobile,gsearch,nonbrand
1,2,NaN,NaN,desktop,gsearch,nonbrand
2,3,NaN,NaN,desktop,gsearch,nonbrand
3,4,NaN,NaN,desktop,gsearch,nonbrand
4,5,NaN,NaN,mobile,gsearch,nonbrand
...,...,...,...,...,...,...
472866,472867,NaN,NaN,desktop,gsearch,brand
472867,472868,NaN,NaN,mobile,bsearch,nonbrand
472868,472869,NaN,NaN,mobile,gsearch,nonbrand
472869,472870,NaN,NaN,desktop,gsearch,nonbrand
472870,472871,NaN,NaN,mobile,NaN,NaN

In [45]:
device_type_info = marketing_info.groupby(['device_type'], as_index=False).agg(
    sessions = ('website_session_id', 'count'),
    orders = ('order_id', 'count')
)
device_type_info['conversion_rate'] = (device_type_info['orders']/ device_type_info['sessions'] * 100).round(2)

In [46]:
device_type_info

  device_type  sessions  orders  conversion_rate
0     desktop    327027   27805             8.50
1      mobile    145844    4508             3.09

In [47]:
utm_source_info = marketing_info.groupby(['utm_source'], as_index=False).agg(
    sessions = ('website_session_id', 'count'),
    orders = ('order_id', 'count')
)
utm_source_info['conversion_rate'] = (utm_source_info['orders']/ utm_source_info['sessions'] * 100).round(2)

In [48]:
utm_source_info

   utm_source  sessions  orders  conversion_rate
0     bsearch     62823    4519             7.19
1     gsearch    316035   21333             6.75
2  socialbook     10685     343             3.21

In [49]:
utm_campaign_info = marketing_info.groupby(['utm_campaign'], as_index=False).agg(
    sessions = ('website_session_id', 'count'),
    orders = ('order_id', 'count')
)
utm_campaign_info['conversion_rate'] = (utm_campaign_info['orders']/ utm_campaign_info['sessions'] * 100).round(2)

In [50]:
utm_campaign_info

       utm_campaign  sessions  orders  conversion_rate
0             brand     41243    3212             7.79
1  desktop_targeted      5590     288             5.15
2          nonbrand    337615   22640             6.71
3             pilot      5095      55             1.08

In [51]:
'''
Marketing Insights

- Desktop users purchased over 5x more products compared to mobile users and has nearly triple the conversion rate
- The majority of purchases originated through gsearch, although bsearch had a higher conversion rate
- The nonbrand campaign generated the highest number of purchases, while the brand campaign achieved the highest conversion rate

'''

'\nMarketing Insights\n\n- Desktop users purchased over 5x more products compared to mobile users and has nearly triple the conversion rate\n- The majority of purchases originated through gsearch, although bsearch had a higher conversion rate\n- The nonbrand campaign generated the highest number of purchases, while the brand campaign achieved the highest conversion rate\n\n'

In [52]:
customer_analysis = pd.read_sql('''
SELECT
    user_id,
    COUNT(order_id) as total_orders
FROM orders
GROUP BY user_id                                 
                                ''', conn)

In [53]:
customer_analysis

       user_id  total_orders
0           13             1
1           20             1
2           59             1
3          104             1
4          147             1
...        ...           ...
31691   394231             1
31692   394255             1
31693   394257             1
31694   394268             1
31695   394273             1

[31696 rows x 2 columns]

In [54]:
repeat_customers = len(customer_analysis[customer_analysis['total_orders'] > 1])
total_customers = len(customer_analysis)
repeat_customer_rate = round((repeat_customers/total_customers * 100), 2)

In [55]:
'''
Customer Insights

- Repeat Customers = 591
- Total Customers = 31696
- Repeat Customer Rate = 1.86 %

The vast majority of customers placed only a single order during the period analysed, with only 1.86% returning to make additional purchases.

'''

'\nCustomer Insights\n\n- Repeat Customers = 591\n- Total Customers = 31696\n- Repeat Customer Rate = 1.86 %\n\nThe vast majority of customers placed only a single order during the period analysed, with only 1.86% returning to make additional purchases.\n\n'

In [56]:
'''
Business Recoomendations

1) Investigate The Birthday Sugar Panda Refund Rate

Finding:

- Despite being a new product on the line it has the highgest refund rate at 6.04%.

Recommendation:

Investigate customer feedback, experience and the fulfilment process to identify why there is a high refund rate.

2) Improve The Mobile Customer Experience

Finding:

- The desktop conversion rate is more than double that of mobile conversion rate, at 8.5%.

Recommendation:

- Review mobile website and checkout experience to identify places where conversions are being reduced.

3) Review The Pilot Utm Campaign

Finding: 

- The conversion rate for the Pilot campaign is only 1.05% which is atleast 5 times smaller than the other 3 campaigns.

Recommendation:

- Review campaign targetting and landing pages before investing additional recources into this campaign.

4) Continue Investing Into Gsearch

Finding:

- Gsearch had the highest number of sessions which can lead to more customers and conversions to the store.

Recommendation:

- Continue investing into Gsearch while monitoring conversions to ensure spending stays effective.

5) Continue Promoting Original Mr. Fuzzy

Finding:

Original Mr. Fuzzy generated the highest revenue and profit throughout the analysis period.

Recommendation:

Continue promoting Original Mr. Fuzzy as the main product, while exploring for ways in which to cross sell newer products.

'''

'\nBusiness Recoomendations\n\n1) Investigate The Birthday Sugar Panda Refund Rate\n\nFinding:\n\n- Despite being a new product on the line it has the highgest refund rate at 6.04%.\n\nRecommendation:\n\nInvestigate customer feedback, experience and the fulfilment process to identify why there is a high refund rate.\n\n2) Improve The Mobile Customer Experience\n\nFinding:\n\n- The desktop conversion rate is more than double that of mobile conversion rate, at 8.5%.\n\nRecommendation:\n\n- Review mobile website and checkout experience to identify places where conversions are being reduced.\n\n3) Review The Pilot Utm Campaign\n\nFinding: \n\n- The conversion rate for the Pilot campaign is only 1.05% which is atleast 5 times smaller than the other 3 campaigns.\n\nRecommendation:\n\n- Review campaign targetting and landing pages before investing additional recources into this campaign.\n\n4) Continue Investing Into Gsearch\n\nFinding:\n\n- Gsearch had the highest number of sessions which can lead to more customers and conversions to the store.\n\nRecommendation:\n\n- Continue investing into Gsearch while monitoring conversions to ensure spending stays effective.\n\n5) Continue Promoting Original Mr. Fuzzy\n\nFinding:\n\nOriginal Mr. Fuzzy generated the highest revenue and profit throughout the analysis period.\n\nRecommendation:\n\nContinue promoting Original Mr. Fuzzy as the main product, while exploring for ways in which to cross sell newer products.\n\n'

In [63]:
len(website_session)

472871

In [ ]:
web